#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)
OUTFILE="$ROOT_DIR/SPECIALIZED_TEST_RESULTS.md"
TMPDIR=$(mktemp -d)

echo "# PolyGuard Specialized Test Results" > "$OUTFILE"
echo "Generated at: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$OUTFILE"
echo "" >> "$OUTFILE"

append_section() {
  local title="$1"; shift
  echo "## $title" >> "$OUTFILE"
  echo '```' >> "$OUTFILE"
  cat "$TMPDIR/$title.log" >> "$OUTFILE" 2>/dev/null || true
  echo '```' >> "$OUTFILE"
  echo "" >> "$OUTFILE"
}

# 1) Security static analysis (Slither)
echo "Running Slither static analysis (best-effort)..."
(
  set +e
  slither . --json "$TMPDIR/slither.json" > "$TMPDIR/slither.log" 2>&1
) || true
[ -f "$TMPDIR/slither.json" ] && jq -r '.results' "$TMPDIR/slither.json" > "$TMPDIR/slither_summary.json" 2>/dev/null || true

# save slither output
append_section "Slither"

# 2) Mythril symbolic analysis (best-effort)
echo "Running Mythril symbolic analysis (best-effort)..."
(
  set +e
  myth analyze -x . --output json > "$TMPDIR/mythril.json" 2>"$TMPDIR/mythril.log"
) || true
append_section "Mythril"

# 3) Python backend tests (pytest)
echo "Running pytest for backend..."
(
  set +e
  export PYTHONPATH=backend
  pytest -q backend/tests -q --maxfail=1 > "$TMPDIR/pytest.log" 2>&1 || true
) || true
append_section "Pytest"

# 4) Rust crate build & tests
echo "Running cargo build/test for core crates..."
(
  set +e
  cargo build --manifest-path crates/polyguard-core-engine/Cargo.toml --release > "$TMPDIR/cargo_core_build.log" 2>&1 || true
  cargo test --manifest-path crates/polyguard-core-engine/Cargo.toml --no-run > "$TMPDIR/cargo_core_test.log" 2>&1 || true
  cargo build --manifest-path crates/polyguard-rpc-proxy/Cargo.toml --release > "$TMPDIR/cargo_rpc_build.log" 2>&1 || true
) || true
append_section "Cargo_Build_Core"
append_section "Cargo_Build_RPC"

# 5) Frontend lint & typecheck
echo "Running frontend typecheck (tsc) and lint (best-effort)..."
(
  set +e
  if [ -f package.json ]; then
    npm ci --no-audit --no-fund > "$TMPDIR/npm_install.log" 2>&1 || true
    npm run lint > "$TMPDIR/npm_lint.log" 2>&1 || true
  else
    echo "No package.json found" > "$TMPDIR/npm_lint.log"
  fi
) || true
append_section "Frontend_Lint"

# 6) Simple RPC proxy smoke (if binary exists)
echo "Checking RPC proxy binary presence..."
(
  set +e
  if [ -f target/release/polyguard-rpc-proxy ] || [ -f crates/polyguard-rpc-proxy/target/release/polyguard-rpc-proxy ]; then
    echo "RPC proxy binary exists" > "$TMPDIR/rpc_proxy.log"
  else
    echo "RPC proxy binary not built" > "$TMPDIR/rpc_proxy.log"
  fi
) || true
append_section "RPC_Proxy"

# 7) ML kernel checks (vectorizer)
echo "Running ML kernel quick checks (best-effort)..."
(
  set +e
  if [ -f ml-kernel/python-vectorizer/requirements.txt ]; then
    python -m pip install -r ml-kernel/python-vectorizer/requirements.txt > "$TMPDIR/ml_install.log" 2>&1 || true
    python - <<PY > "$TMPDIR/ml_check.log" 2>&1 || true
import importlib
import sys
reqs = ['torch','numpy']
for r in reqs:
    try:
        importlib.import_module(r)
        print(r + ' OK')
    except Exception as e:
        print(r + ' MISSING: ' + str(e))
PY
  else
    echo "No ML kernel requirements found" > "$TMPDIR/ml_check.log"
  fi
) || true
append_section "ML_Kernel"

# Upload summary of critical findings
echo "Summary of findings:" >> "$OUTFILE"
if grep -q "CRITICAL" "$TMPDIR/pytest.log" 2>/dev/null || grep -q "CRITICAL" "$TMPDIR/slither.log" 2>/dev/null || grep -q "CRITICAL" "$TMPDIR/mythril.log" 2>/dev/null; then
  echo "One or more critical findings detected. See sections above for details." >> "$OUTFILE"
else
  echo "No CRITICAL markers found in quick scans. Full audit recommended for production." >> "$OUTFILE"
fi

# Make file writeable and show head
chmod 644 "$OUTFILE"

# Optionally commit results back to repo root if running in CI with push rights
if [ -n "${GITHUB_ACTIONS:-}" ]; then
  echo "Committing $OUTFILE back to repository (if changed)..."
  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git checkout -b specialized-test-results || true
  git add "$OUTFILE" || true
  if git diff --staged --quiet; then
    echo "No changes to commit"
  else
    git commit -m "chore(tests): add latest specialized test results\n\nGenerated by CI" || true
    git push origin HEAD || true
  fi
fi

# Print location
echo "Wrote results to $OUTFILE"
